/*
Copyright (c) 2026 SICK AG
SPDX-License-Identifier: MIT
*/

/**
 * @file multiScan100.g.hpp Sensor REST API payload definitions.
 * @warning This file was generated for device 'multiScan100' version '2.4.1'.
 * Do not edit manually!
 */
#pragma once

#include <sick_perception_sdk/sensor_configuration/api/multiScan100/checkCredentials.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/parameterbackup.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/DeviceIdent.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/LocationName.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/SerialNumber.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/FirmwareVersion.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/SetPassword.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/getChallenge.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/changePassword.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/EnableUserLevel.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/OrderNumber.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/DeviceStatus.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/WriteEeprom.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/SoftReset.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/RebootDevice.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/LoadFactoryDefaults.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/LoadApplicationDefaults.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/LastParaDate.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/LastParaTime.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/DoDiagnosisDump.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/GetDiagnosisDumpInfo.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/EtherIPAddress.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/EtherIPGateAddress.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/EtherIPMask.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/EtherAuxEnabled.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/EtherCoLaScanMode.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/EtherAddressingMode.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/EtherDHCPFallback.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/EthernetUpdate.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/httpsStatus.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/certificateBundleInfo.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/removeCertificateBundle.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/setCertificateBundle.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/EtherIPAddressDHCP.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/EtherIPGateAddressDHCP.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/EtherIPMaskDHCP.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/SetWebserverEnabled.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/GetWebserverEnabled.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/EnableLegacyUserLevel.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/EtherMACAddress.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/PowerOnCnt.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/DailyOpHours.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/OpHours.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/DeviceType.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/RunFirmwareUpdate.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/UpdateState.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/CreateParameterBackup.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/SCdevicestate.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/ContaminationConfig.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/ContaminationActiveSectors.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/ContaminationData.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/ContaminationResult.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/ScanDataEthSettings.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/ScanDataEnable.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/ScanDataFormat.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/groundFilterEnable.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/groundFilterThresholds.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/groundFilterType.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/ImuDataEthSettings.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/ImuDataEnable.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/InertialMeasurementUnit.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/CopySensorOrientationFromImu.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/PortConfiguration.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/SetOutput.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/InputState.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/OutputState.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/PortState.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/mResetOutputCounter.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/LEDState.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/LEDEnable.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/FindMe.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/perpendicularDistanceResult.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/FieldEvaluationResult.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/ActivateEvaluationGroup.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/SetFieldEvaluationContour.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/GetFieldEvaluationContour.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/FieldEvaluationGroupState.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/EvaluationConfigState.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/FieldEvaluationApplicationState.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/EnableDetectionHistory.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/EvaluationsToLog.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/ResetDetectionHistory.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/mStartMeasure.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/mStopMeasure.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/AutoStartMeasure.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/bInterlacedMode.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/MCSenseLevel.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/temperatureAlarmConfiguration.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/temperatureAlarmStatus.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/CurrentTempDev.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/LFPparticle.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/LFPmovingAveragingFilter.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/LFPangleRangeFilter.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/LFPradialDistanceRangeFilter.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/LFPcubicareafilter.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/FREchoFilter.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/LFPintervalFilter.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/LFPlayerFilter.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/ScanDataPreformatting.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/SensorPosition.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/TSCRole.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/TSCTCSrvAddr.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/TSCTCtimezone.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/TSCTCupdatetime.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/LSPdatetime.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/LSPsetdatetime.g.hpp>

