/*
Copyright (c) 2026 SICK AG
SPDX-License-Identifier: MIT
*/

/**
 * @file multiScan200.g.hpp Sensor REST API payload definitions.
 * @warning This file was generated for device 'multiScan200' version '0.9.0-c.1+2407.172e2'.
 * Do not edit manually!
 */
#pragma once

#include <sick_perception_sdk/sensor_configuration/api/multiScan200/checkCredentials.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/parameterbackup.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/DeviceIdent.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/CidVersion.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/SOPASVersion.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/LocationName.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/SerialNumber.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/FirmwareVersion.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/SopasInfo.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/NotifyMode.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/GetAccessMode.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/Run.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/GetDescription.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/SetAccessMode.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/SetPassword.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/CheckPassword.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/CIDChecksum.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/SubDevicesExt.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/getChallenge.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/SetUserLevel.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/changePassword.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/GetUserLevelPasswordState.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/SwitchChangeDefaultPasswordDialogState.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/SetPasswordRecoverySecret.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/StartPasswordRecovery.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/CompletePasswordRecovery.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/CancelPasswordRecovery.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/GetPasswordRecoveryStatus.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/EnableUserLevel.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/GetUserLevelInformation.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/GenOpenFile.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/GenCloseFile.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/GenReadFile.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/GenWriteFile.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/GetFileSyncValue.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/GetFileSize.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/TypeCode.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/OrderNumber.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/DeviceStatus.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/RequiredUserAction.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/DeviceName.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/ProjectName.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/ReadEeprom.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/WriteEeprom.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/WriteCalibEeprom.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/SCRebootNeedful.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/SCParamsChanged.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/SCUserInterfaceVariant.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/SoftReset.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/RebootDevice.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/LoadFactoryDefaults.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/LoadApplicationDefaults.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/LoadProductionDefaults.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/SetFilesImmutableFlag.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/GetFilesImmutableFlag.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/GetFilesProtectedByImmutableFlag.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/FDSignature.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/Start2ndStageLoader.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/LogWrite.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/LogEnd.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/LogInfo.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/LogErase.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/ETraceMsg.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/EMsgDebug.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/EMsgInfo.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/EMsgWarning.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/EMsgError.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/EMsgFatal.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/ClearErrorMessages.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/ClearErrorMessagesSickService.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/LastUsername.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/LastParaDate.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/LastParaTime.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/LastUsernameTemp.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/LastParaDateTemp.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/LastParaTimeTemp.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/LastMaintenance.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/NextMaintenance.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/GoReadyCount.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/SetLastUser.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/SystemDump.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/DoDiagnosisDump.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/GetDiagnosisDumpPath.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/GetDiagnosisDumpInfo.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/NotificationList.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/ClearNotifications.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/SystemConfigData.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/ProgramConfigData.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/ProgramData.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/ProgramDataTransferSize.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/ExecuteDownload.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/StatusDownload.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/FinishDownload.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/AbortDownload.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/EtherIPAddress.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/EtherIPGateAddress.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/EtherIPMask.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/EtherIPSpeedDuplex.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/EtherHostIPPort.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/EtherHostCoLaDialect.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/EtherAuxIPPort.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/EtherAuxCoLaDialect.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/EtherAuxEnabled.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/EtherCoLa2Enabled.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/EtherCoLaScanMode.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/EtherAddressingMode.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/EtherDHCPFallback.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/EtherUpdateNeeded.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/EthernetPing.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/EthernetUpdate.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/EtherIPSpeedDuplexNegotiated.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/EtherIPAddressDHCP.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/EtherIPGateAddressDHCP.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/EtherIPMaskDHCP.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/EtherLinkState.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/FileSystemAccess.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/AppEngineVersion.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/AppEngineLockAppDev.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/AppEngineDevSysApps.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/AppEngineDefaultWebpage.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/AppConsoleOutput.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/AppDebugEnvironment.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/AppCommand.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/PluginsFolder.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/httpsStatus.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/certificateBundleInfo.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/removeCertificateBundle.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/setCertificateBundle.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/EnableColaScan.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/EnableExtendedManifest.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/SetWebserverEnabled.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/GetWebserverEnabled.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/SetSSHEnabled.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/isSshEnabled.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/ValidUserLevels.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/EnableLegacyUserLevel.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/acceptDevFirmware.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/DisableEyeSafety.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/DeviceTime.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/EtherMACAddress.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/LedBrightnessFactor.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/LedGammaCorrectionTable.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/StoreCustomerDefaultParameters.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/RestoreUserCustomerParameters.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/StoreUserFactoryParameters.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/RemoveUserFactoryParameters.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/PRODSetDeliveryState.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/PowerOnCnt.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/DailyOpHours.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/OpHours.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/DeviceType.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/Manufacturer.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/OrderNumberCompat.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/HasEthernet.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/RunFirmwareUpdate.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/UpdateState.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/CreateParameterBackup.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/CreateParameterBackupDev.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/SCdevicestate.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/ContaminationConfig.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/ContaminationActiveSectors.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/ContaminationData.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/ContaminationResult.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/treatBlockedSectorsAsErrorSectors.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/dataOutputMode.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/LFPintervalFilter.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/horizontalAngleRangeFilter.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/verticalAngleRangeFilter.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/compactSerializationContent.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/SensorPosition.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/rosFrameId.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/rosParentFrameId.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/rosEndianness.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/rosPointCloud2Content.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/rosNamespace.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/mStartMeasure.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/mStandby.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/mStopMeasure.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/AutoStartMeasure.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/DistMeasState.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/InertialMeasurementUnit.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/CopySensorOrientationFromImu.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/SourceList.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/PortToPinMapping.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/PortConfiguration.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/OutputCommandState.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/SetOutput.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/InputState.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/OutputState.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/PortState.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/mResetOutputCounter.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/LEDState.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/LEDEnable.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/FindMe.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/setLedOverride.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/EvaluationList.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/Eval001.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/Eval002.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/Eval003.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/Eval004.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/Eval005.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/Eval006.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/Eval007.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/Eval008.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/Eval009.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/Eval010.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/Eval011.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/Eval012.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/Eval013.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/Eval014.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/Eval015.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/Eval016.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/Eval017.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/Eval018.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/Eval019.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/Eval020.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/Eval021.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/Eval022.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/Eval023.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/Eval024.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/Eval025.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/Eval026.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/Eval027.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/Eval028.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/Eval029.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/Eval030.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/Eval031.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/Eval032.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/Eval033.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/Eval034.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/Eval035.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/Eval036.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/Eval037.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/Eval038.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/Eval039.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/Eval040.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/Eval041.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/Eval042.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/Eval043.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/Eval044.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/Eval045.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/Eval046.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/Eval047.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/Eval048.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/Volume001.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/Volume002.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/Volume003.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/Volume004.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/Volume005.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/Volume006.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/Volume007.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/Volume008.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/Volume009.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/Volume010.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/Volume011.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/Volume012.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/Volume013.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/Volume014.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/Volume015.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/Volume016.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/Volume017.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/Volume018.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/Volume019.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/Volume020.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/Volume021.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/Volume022.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/Volume023.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/Volume024.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/Volume025.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/Volume026.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/Volume027.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/Volume028.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/Volume029.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/Volume030.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/Volume031.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/Volume032.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/Volume033.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/Volume034.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/Volume035.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/Volume036.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/Volume037.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/Volume038.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/Volume039.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/Volume040.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/Volume041.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/Volume042.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/Volume043.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/Volume044.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/Volume045.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/Volume046.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/Volume047.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/Volume048.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/FieldEvaluationResult.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/MaxVolumeAmount.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/MaxEvaluationAmount.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/ActivateEvaluationGroup.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/SetFieldEvaluationContour.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/PolarProjectionParameters.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/PolarProjectionVectors.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/EvaluationGroupMapping.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/FieldEvaluationGroupState.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/InputActivationSynchronizationTime.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/EvaluationConfigState.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/FieldEvaluationApplicationState.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/MaxActiveEvaluationsAmount.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/MaxActiveBeamsAmount.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/ObjectDetectionDiagnosis.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/bIsObjectDetectionInstalled.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/ActiveViewer.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/outputVisualizationContent.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/SetActiveViewer.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/setOutputVisualizationContent.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/ScanConfig.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/PerformanceProfileNumber.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/SetScanConfigList.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/horizontalFieldOfViewStartAngle.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/bloomingFilter.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/particleFilter.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/ambientPixelCountVertical.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/SensitivityMode.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/FREchoFilter.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/temperatureAlarmConfiguration.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/temperatureAlarmStatus.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/CurrentTempDev.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/CPULoad.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/TSCRole.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/TSCTCSrvAddr.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/TSCTCtimezone.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/TSCTCupdatetime.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/LSPdatetime.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/LSPsetdatetime.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/CreateSessionToken.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/GetSessionTokenInfo.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/RenewSessionToken.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/TerminateSession.g.hpp>

