/*
Copyright (c) 2026 SICK AG
SPDX-License-Identifier: MIT
*/

/**
 * @file picoScan100.g.hpp Sensor REST API payload definitions.
 * @warning This file was generated for device 'picoScan100' version '2.2.0'.
 * Do not edit manually!
 */
#pragma once

#include <sick_perception_sdk/sensor_configuration/api/picoScan100/checkCredentials.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/parameterbackup.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/DeviceIdent.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/LocationName.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/SerialNumber.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/FirmwareVersion.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/SetPassword.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/getChallenge.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/changePassword.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/EnableUserLevel.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/OrderNumber.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/DeviceStatus.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/WriteEeprom.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/SCdevicestate.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/SoftReset.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/RebootDevice.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/LoadFactoryDefaults.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/LoadApplicationDefaults.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/LastParaDate.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/LastParaTime.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/DoDiagnosisDump.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/GetDiagnosisDumpInfo.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/InputState.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/OutputState.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/PortState.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/mResetOutputCounter.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/EtherIPAddress.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/EtherIPGateAddress.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/EtherIPMask.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/EtherAuxEnabled.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/EtherCoLaScanMode.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/EtherAddressingMode.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/EtherDHCPFallback.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/EthernetUpdate.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/EtherIPAddressDHCP.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/EtherIPGateAddressDHCP.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/EtherIPMaskDHCP.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/httpsStatus.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/certificateBundleInfo.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/removeCertificateBundle.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/setCertificateBundle.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/SetWebserverEnabled.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/GetWebserverEnabled.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/EnableLegacyUserLevel.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/EtherMACAddress.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/PowerOnCnt.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/DailyOpHours.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/OpHours.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/DeviceType.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/RunFirmwareUpdate.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/UpdateState.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/CreateParameterBackup.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/ContaminationConfig.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/ContaminationData.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/ContaminationResult.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/ScanDataEthSettings.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/ScanDataEnable.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/ScanDataFormat.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/rosFrameId.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/rosParentFrameId.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/rosNamespace.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/EncoderDataEthSettings.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/EncoderDataEnable.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/EncSetting.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/ActualEncPosition1Enable.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/ActualEncPosition2Enable.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/EncResolution.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/mResetEncoderIncrement.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/ImuDataEthSettings.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/ImuDataEnable.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/InertialMeasurementUnit.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/PortConfiguration.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/SetOutput.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/LEDState.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/LEDEnable.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/FindMe.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/LFTchecksum.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/FieldEvaluationResult.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/ActivateEvaluationGroup.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/SetFieldEvaluationContour.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/GetFieldEvaluationContour.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/EvaluationGroupType.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/FieldEvaluationGroupState.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/EnableDetectionHistory.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/EvaluationsToLog.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/ResetDetectionHistory.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/StartTeachIn.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/StopTeachIn.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/perpendicularDistanceResult.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/mStartMeasure.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/mStandby.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/mStopMeasure.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/AutoStartMeasure.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/MCSenseLevel.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/PerformanceProfileNumber.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/ScanConfig.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/EnableLongRangeMode.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/SensitivityMode.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/temperatureAlarmConfiguration.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/temperatureAlarmStatus.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/CurrentTempDev.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/LFPparticle.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/LFPmovingAveragingFilter.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/LFPangleRangeFilter.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/LFPradialDistanceRangeFilter.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/LFPcubicareafilter.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/FREchoFilter.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/LFPintervalFilter.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/SensorPosition.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/TSCRole.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/TSCTCSrvAddr.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/TSCTCtimezone.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/TSCTCupdatetime.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/LSPdatetime.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/LSPsetdatetime.g.hpp>

