/*
Copyright (c) 2026 SICK AG
SPDX-License-Identifier: MIT
*/

/**
 * @file 2_4_2_0R.g.hpp Sensor REST API payload definitions.
 * @warning This file was generated for device 'multiScan100' version '2.4.2.0R'.
 * Do not edit manually!
 */
#pragma once

#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/checkCredentials.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/parameterbackup.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/DeviceIdent.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/LocationName.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/SerialNumber.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/FirmwareVersion.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/SetPassword.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/getChallenge.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/changePassword.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/EnableUserLevel.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/OrderNumber.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/DeviceStatus.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/WriteEeprom.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/SoftReset.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/RebootDevice.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/LoadFactoryDefaults.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/LoadApplicationDefaults.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/LastParaDate.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/LastParaTime.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/DoDiagnosisDump.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/GetDiagnosisDumpInfo.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/EtherIPAddress.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/EtherIPGateAddress.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/EtherIPMask.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/EtherAuxEnabled.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/EtherCoLaScanMode.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/EtherAddressingMode.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/EtherDHCPFallback.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/EthernetUpdate.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/httpsStatus.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/certificateBundleInfo.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/removeCertificateBundle.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/setCertificateBundle.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/EtherIPAddressDHCP.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/EtherIPGateAddressDHCP.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/EtherIPMaskDHCP.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/SetWebserverEnabled.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/GetWebserverEnabled.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/EnableLegacyUserLevel.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/EtherMACAddress.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/PowerOnCnt.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/DailyOpHours.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/OpHours.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/DeviceType.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/RunFirmwareUpdate.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/UpdateState.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/CreateParameterBackup.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/SCdevicestate.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/ContaminationConfig.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/ContaminationActiveSectors.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/ContaminationData.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/ContaminationResult.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/ScanDataEthSettings.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/ScanDataEnable.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/ScanDataFormat.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/groundFilterEnable.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/groundFilterThresholds.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/groundFilterType.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/ImuDataEthSettings.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/ImuDataEnable.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/InertialMeasurementUnit.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/CopySensorOrientationFromImu.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/PortConfiguration.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/SetOutput.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/InputState.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/OutputState.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/PortState.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/mResetOutputCounter.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/LEDState.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/LEDEnable.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/FindMe.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/perpendicularDistanceResult.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/FieldEvaluationResult.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/ActivateEvaluationGroup.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/SetFieldEvaluationContour.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/GetFieldEvaluationContour.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/FieldEvaluationGroupState.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/EvaluationConfigState.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/FieldEvaluationApplicationState.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/EnableDetectionHistory.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/EvaluationsToLog.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/ResetDetectionHistory.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/mStartMeasure.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/mStopMeasure.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/AutoStartMeasure.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/bInterlacedMode.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/MCSenseLevel.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/temperatureAlarmConfiguration.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/temperatureAlarmStatus.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/CurrentTempDev.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/LFPparticle.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/LFPmovingAveragingFilter.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/LFPangleRangeFilter.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/LFPradialDistanceRangeFilter.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/LFPcubicareafilter.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/FREchoFilter.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/LFPintervalFilter.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/LFPlayerFilter.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/ScanDataPreformatting.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/SensorPosition.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/TSCRole.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/TSCTCSrvAddr.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/TSCTCtimezone.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/TSCTCupdatetime.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/LSPdatetime.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/LSPsetdatetime.g.hpp>

