/*
Copyright (c) 2026 SICK AG
SPDX-License-Identifier: MIT
*/

/**
 * @file 2_4_1.g.hpp Sensor REST API payload definitions.
 * @warning This file was generated for device 'multiScan100' version '2.4.1'.
 * Do not edit manually!
 */
#pragma once

#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_1/checkCredentials.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_1/parameterbackup.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_1/DeviceIdent.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_1/LocationName.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_1/SerialNumber.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_1/FirmwareVersion.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_1/SetPassword.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_1/getChallenge.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_1/changePassword.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_1/EnableUserLevel.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_1/OrderNumber.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_1/DeviceStatus.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_1/WriteEeprom.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_1/SoftReset.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_1/RebootDevice.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_1/LoadFactoryDefaults.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_1/LoadApplicationDefaults.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_1/LastParaDate.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_1/LastParaTime.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_1/DoDiagnosisDump.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_1/GetDiagnosisDumpInfo.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_1/EtherIPAddress.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_1/EtherIPGateAddress.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_1/EtherIPMask.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_1/EtherAuxEnabled.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_1/EtherCoLaScanMode.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_1/EtherAddressingMode.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_1/EtherDHCPFallback.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_1/EthernetUpdate.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_1/httpsStatus.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_1/certificateBundleInfo.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_1/removeCertificateBundle.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_1/setCertificateBundle.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_1/EtherIPAddressDHCP.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_1/EtherIPGateAddressDHCP.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_1/EtherIPMaskDHCP.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_1/SetWebserverEnabled.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_1/GetWebserverEnabled.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_1/EnableLegacyUserLevel.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_1/EtherMACAddress.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_1/PowerOnCnt.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_1/DailyOpHours.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_1/OpHours.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_1/DeviceType.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_1/RunFirmwareUpdate.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_1/UpdateState.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_1/CreateParameterBackup.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_1/SCdevicestate.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_1/ContaminationConfig.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_1/ContaminationActiveSectors.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_1/ContaminationData.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_1/ContaminationResult.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_1/ScanDataEthSettings.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_1/ScanDataEnable.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_1/ScanDataFormat.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_1/groundFilterEnable.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_1/groundFilterThresholds.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_1/groundFilterType.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_1/ImuDataEthSettings.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_1/ImuDataEnable.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_1/InertialMeasurementUnit.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_1/CopySensorOrientationFromImu.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_1/PortConfiguration.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_1/SetOutput.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_1/InputState.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_1/OutputState.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_1/PortState.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_1/mResetOutputCounter.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_1/LEDState.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_1/LEDEnable.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_1/FindMe.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_1/perpendicularDistanceResult.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_1/FieldEvaluationResult.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_1/ActivateEvaluationGroup.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_1/SetFieldEvaluationContour.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_1/GetFieldEvaluationContour.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_1/FieldEvaluationGroupState.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_1/EvaluationConfigState.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_1/FieldEvaluationApplicationState.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_1/EnableDetectionHistory.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_1/EvaluationsToLog.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_1/ResetDetectionHistory.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_1/mStartMeasure.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_1/mStopMeasure.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_1/AutoStartMeasure.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_1/bInterlacedMode.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_1/MCSenseLevel.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_1/temperatureAlarmConfiguration.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_1/temperatureAlarmStatus.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_1/CurrentTempDev.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_1/LFPparticle.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_1/LFPmovingAveragingFilter.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_1/LFPangleRangeFilter.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_1/LFPradialDistanceRangeFilter.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_1/LFPcubicareafilter.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_1/FREchoFilter.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_1/LFPintervalFilter.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_1/LFPlayerFilter.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_1/ScanDataPreformatting.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_1/SensorPosition.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_1/TSCRole.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_1/TSCTCSrvAddr.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_1/TSCTCtimezone.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_1/TSCTCupdatetime.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_1/LSPdatetime.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_1/LSPsetdatetime.g.hpp>

