/*
Copyright (c) 2026 SICK AG
SPDX-License-Identifier: MIT
*/

/**
 * @file 2_4_2_0R.nlohmann_json.g.hpp Sensor REST API payload definitions.
 * @warning This file was generated for device 'multiScan100' version '2.4.2.0R'.
 * Do not edit manually!
 */
#pragma once

#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/checkCredentials.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/parameterbackup.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/DeviceIdent.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/LocationName.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/SerialNumber.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/FirmwareVersion.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/SetPassword.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/getChallenge.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/changePassword.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/EnableUserLevel.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/OrderNumber.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/DeviceStatus.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/WriteEeprom.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/SoftReset.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/RebootDevice.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/LoadFactoryDefaults.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/LoadApplicationDefaults.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/LastParaDate.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/LastParaTime.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/DoDiagnosisDump.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/GetDiagnosisDumpInfo.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/EtherIPAddress.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/EtherIPGateAddress.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/EtherIPMask.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/EtherAuxEnabled.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/EtherCoLaScanMode.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/EtherAddressingMode.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/EtherDHCPFallback.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/EthernetUpdate.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/httpsStatus.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/certificateBundleInfo.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/removeCertificateBundle.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/setCertificateBundle.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/EtherIPAddressDHCP.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/EtherIPGateAddressDHCP.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/EtherIPMaskDHCP.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/SetWebserverEnabled.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/GetWebserverEnabled.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/EnableLegacyUserLevel.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/EtherMACAddress.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/PowerOnCnt.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/DailyOpHours.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/OpHours.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/DeviceType.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/RunFirmwareUpdate.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/UpdateState.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/CreateParameterBackup.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/SCdevicestate.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/ContaminationConfig.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/ContaminationActiveSectors.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/ContaminationData.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/ContaminationResult.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/ScanDataEthSettings.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/ScanDataEnable.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/ScanDataFormat.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/groundFilterEnable.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/groundFilterThresholds.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/groundFilterType.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/ImuDataEthSettings.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/ImuDataEnable.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/InertialMeasurementUnit.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/CopySensorOrientationFromImu.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/PortConfiguration.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/SetOutput.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/InputState.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/OutputState.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/PortState.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/mResetOutputCounter.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/LEDState.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/LEDEnable.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/FindMe.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/perpendicularDistanceResult.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/FieldEvaluationResult.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/ActivateEvaluationGroup.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/SetFieldEvaluationContour.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/GetFieldEvaluationContour.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/FieldEvaluationGroupState.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/EvaluationConfigState.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/FieldEvaluationApplicationState.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/EnableDetectionHistory.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/EvaluationsToLog.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/ResetDetectionHistory.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/mStartMeasure.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/mStopMeasure.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/AutoStartMeasure.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/bInterlacedMode.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/MCSenseLevel.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/temperatureAlarmConfiguration.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/temperatureAlarmStatus.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/CurrentTempDev.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/LFPparticle.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/LFPmovingAveragingFilter.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/LFPangleRangeFilter.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/LFPradialDistanceRangeFilter.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/LFPcubicareafilter.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/FREchoFilter.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/LFPintervalFilter.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/LFPlayerFilter.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/ScanDataPreformatting.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/SensorPosition.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/TSCRole.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/TSCTCSrvAddr.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/TSCTCtimezone.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/TSCTCupdatetime.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/LSPdatetime.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_2_0R/LSPsetdatetime.nlohmann_json.g.hpp>

