/*
Copyright (c) 2026 SICK AG
SPDX-License-Identifier: MIT
*/

/**
 * @file 2_2_1.nlohmann_json.g.hpp Sensor REST API payload definitions.
 * @warning This file was generated for device 'picoScan150' version '2.2.1'.
 * Do not edit manually!
 */
#pragma once

#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/checkCredentials.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/parameterbackup.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/DeviceIdent.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/LocationName.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/SerialNumber.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/FirmwareVersion.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/SetPassword.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/getChallenge.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/changePassword.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/EnableUserLevel.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/OrderNumber.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/DeviceStatus.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/WriteEeprom.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/SCdevicestate.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/SoftReset.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/RebootDevice.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/LoadFactoryDefaults.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/LoadApplicationDefaults.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/LastParaDate.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/LastParaTime.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/DoDiagnosisDump.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/GetDiagnosisDumpInfo.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/InputState.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/OutputState.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/PortState.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/mResetOutputCounter.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/EtherIPAddress.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/EtherIPGateAddress.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/EtherIPMask.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/EtherAuxEnabled.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/EtherCoLaScanMode.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/EtherAddressingMode.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/EtherDHCPFallback.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/EthernetUpdate.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/EtherIPAddressDHCP.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/EtherIPGateAddressDHCP.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/EtherIPMaskDHCP.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/httpsStatus.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/certificateBundleInfo.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/removeCertificateBundle.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/setCertificateBundle.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/SetWebserverEnabled.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/GetWebserverEnabled.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/EnableLegacyUserLevel.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/EtherMACAddress.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/PowerOnCnt.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/DailyOpHours.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/OpHours.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/DeviceType.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/RunFirmwareUpdate.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/UpdateState.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/CreateParameterBackup.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/RestoreParameterBackup.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/ContaminationConfig.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/ContaminationData.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/ContaminationResult.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/ScanDataEthSettings.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/ScanDataEnable.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/ScanDataFormat.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/rosFrameId.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/rosParentFrameId.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/rosNamespace.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/EncoderDataEthSettings.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/EncoderDataEnable.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/EncSetting.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/ActualEncPosition1Enable.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/ActualEncPosition2Enable.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/EncResolution.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/mResetEncoderIncrement.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/ImuDataEthSettings.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/ImuDataEnable.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/InertialMeasurementUnit.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/PortConfiguration.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/SetOutput.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/LEDState.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/LEDEnable.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/FindMe.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/LFTchecksum.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/FieldEvaluationResult.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/ActivateEvaluationGroup.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/SetFieldEvaluationContour.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/GetFieldEvaluationContour.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/EvaluationGroupType.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/FieldEvaluationGroupState.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/EnableDetectionHistory.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/EvaluationsToLog.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/ResetDetectionHistory.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/StartTeachIn.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/StopTeachIn.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/perpendicularDistanceResult.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/mStartMeasure.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/mStandby.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/mStopMeasure.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/AutoStartMeasure.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/MCSenseLevel.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/PerformanceProfileNumber.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/ScanConfig.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/EnableLongRangeMode.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/SensitivityMode.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/temperatureAlarmConfiguration.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/temperatureAlarmStatus.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/CurrentTempDev.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/LFPparticle.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/LFPmovingAveragingFilter.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/LFPangleRangeFilter.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/LFPradialDistanceRangeFilter.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/LFPcubicareafilter.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/FREchoFilter.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/LFPintervalFilter.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/SensorPosition.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/TSCRole.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/TSCTCSrvAddr.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/TSCTCtimezone.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/TSCTCupdatetime.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/LSPdatetime.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_2_1/LSPsetdatetime.nlohmann_json.g.hpp>

